trigger:
- main

variables:
  # Docker image details
  imageName: 'myapp'
  tag: 'latest'
  acr_repo: repo_ver2

stages:
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: Build
    displayName: 'Build and Push'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build -- --prod
      displayName: 'Install dependencies and build Angular project'

    - task: Docker@2
      inputs:
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: $(tag)
        repository: $(imageName)
      displayName: 'Build Docker Image'

    - task: Docker@2
      inputs:
        command: 'login'
        containerRegistry: 'pitcontainertestt'  # Replace with your actual container registry service connection name
      displayName: 'Login to ACR'

    - task: Docker@2
      inputs:
        command: 'push'
        repository: $(acr_repo)
        tags: $(tag)
      displayName: 'Push Docker Image'
