trigger:
- main

variables:
  # Docker image details
  imageName: 'myapp'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: 'Build Docker Image'
  jobs:
  - job: Build
    displayName: 'Build'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build -- --prod
      displayName: 'Install dependencies and build Angular project'
      continueOnError: true  # Add this to continue the pipeline even if there are errors in this step

    - task: Docker@2
      inputs:
        containerRegistry: ''
        repository: '$(imageName)'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
      displayName: 'Build Docker Image'
